name = "fuzd-worker"
main = "src/index.ts"
compatibility_date = "2023-05-18"

[durable_objects]
bindings = [
  { name = "SCHEDULER", class_name = "SchedulerDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["SchedulerDO"]
