name = "dreveal-worker"
main = "src/index.ts"
compatibility_date = "2023-05-18"
format = "modules"

[durable_objects]
bindings = [
  { name = "EXECUTOR", class_name = "ExecutorDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["ExecutorDO"]
