name = "fuzd-worker"
main = "src/index.ts"
compatibility_date = "2023-05-18"

compatibility_flags = [ "nodejs_compat" ] # for node:async_hooks

#[vars]
# The necessary secrets are:
# - HD_MNEMONIC
# - CHAIN_0x<CHAINID>
# see in .dev.vars.default
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these

# for dev
#[durable_objects]
#bindings = [
#  { name = "SCHEDULER", class_name = "SchedulerDO" }
#]


[triggers]
crons = ["* * * * *", "*/1 * * * *"]

[[migrations]]
tag = "v1"
new_classes = ["SchedulerDO"]


[env.production]
durable_objects.bindings = [
   { name = "SCHEDULER", class_name = "SchedulerDO" }
]

[env.dev]
durable_objects.bindings = [
   { name = "SCHEDULER", class_name = "SchedulerDO" }
]

[env.composablelabs]
durable_objects.bindings = [
   { name = "SCHEDULER", class_name = "SchedulerDO" }
]

[env.sepolia]
durable_objects.bindings = [
   { name = "SCHEDULER", class_name = "SchedulerDO" }
]

[env.alpha1test]
durable_objects.bindings = [
   { name = "SCHEDULER", class_name = "SchedulerDO" }
]

